name: Deploy
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: convictional/trigger-workflow-and-wait@v1.3.0
        with:
          owner: vmishra2305
          repo: TestGladly
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow_file_name: receiving.yml
