# This is a basic workflow to help you get started with Actions

name: run gladly automated test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  run-gladly-test:
    runs-on: macos-latest

    steps:
      - name: repository dispatch
        uses: peter-evans/repository-dispatch@v2
        with: 
          token: ${{secrets.REPO_ACCESS_TOKEN}}
          repository: vmishra2305/TestGladly
          event-type: my-event
          client-payload: '{"github": ${{toJson(github)}}}'

